version: '3.8'

services:
  nats-single-tls:
    image: nats:2.10-alpine
    container_name: nats-single-tls
    hostname: nats-server
    ports:
      - "4222:4222"      # NATS TLS
      - "8222:8222"      # HTTP Monitoring
      - "8080:8080"      # WebSocket TLS
    volumes:
      - ./nats-server-tls.conf:/etc/nats/nats-server.conf:ro
      - ./certs:/etc/nats/certs:ro
      - ./data/jetstream:/data/jetstream
      - ./logs:/var/log/nats
    command: ["-c", "/etc/nats/nats-server.conf"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - NATS_SERVER_NAME=nats-single-tls
    networks:
      - nats-network

networks:
  nats-network:
    driver: bridge
